openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/orders:
    get:
      summary: 'Get orders list'
      operationId: getOrdersList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      order_number: '12345'
                      total_amount: 100.5
                      status: pending
                      items:
                        -
                          id: 1
                          name: null
                          quantity: 1
                          price: 50.25
                        -
                          id: 2
                          name: null
                          quantity: 2
                          price: 25.12
                      created_at: '2024-12-20T16:11:24.000000Z'
                      updated_at: '2024-12-20T16:11:24.000000Z'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        order_number: '12345'
                        total_amount: 100.5
                        status: pending
                        items:
                          -
                            id: 1
                            name: null
                            quantity: 1
                            price: 50.25
                          -
                            id: 2
                            name: null
                            quantity: 2
                            price: 25.12
                        created_at: '2024-12-20T16:11:24.000000Z'
                        updated_at: '2024-12-20T16:11:24.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        order_number:
                          type: string
                          example: '12345'
                        total_amount:
                          type: number
                          example: 100.5
                        status:
                          type: string
                          example: pending
                        items:
                          type: array
                          example:
                            -
                              id: 1
                              name: null
                              quantity: 1
                              price: 50.25
                            -
                              id: 2
                              name: null
                              quantity: 2
                              price: 25.12
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: 1
                              name:
                                type: string
                                example: null
                              quantity:
                                type: integer
                                example: 1
                              price:
                                type: number
                                example: 50.25
                        created_at:
                          type: string
                          example: '2024-12-20T16:11:24.000000Z'
                        updated_at:
                          type: string
                          example: '2024-12-20T16:11:24.000000Z'
      tags:
        - Order
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: 'Status of the order.'
                  example: pending
                  nullable: true
      security: []
    post:
      summary: 'Create order'
      operationId: createOrder
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    order_number: '12345'
                    total_amount: 100.5
                    status: pending
                    items:
                      -
                        id: 1
                        name: null
                        quantity: 1
                        price: 50.25
                      -
                        id: 2
                        name: null
                        quantity: 2
                        price: 25.12
                    created_at: '2024-12-20T16:05:18.000000Z'
                    updated_at: '2024-12-20T16:05:18.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      order_number:
                        type: string
                        example: '12345'
                      total_amount:
                        type: number
                        example: 100.5
                      status:
                        type: string
                        example: pending
                      items:
                        type: array
                        example:
                          -
                            id: 1
                            name: null
                            quantity: 1
                            price: 50.25
                          -
                            id: 2
                            name: null
                            quantity: 2
                            price: 25.12
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: null
                            quantity:
                              type: integer
                              example: 1
                            price:
                              type: number
                              example: 50.25
                      created_at:
                        type: string
                        example: '2024-12-20T16:05:18.000000Z'
                      updated_at:
                        type: string
                        example: '2024-12-20T16:05:18.000000Z'
      tags:
        - Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_number:
                  type: string
                  description: 'Order number.'
                  example: '123456'
                  nullable: false
                total_amount:
                  type: number
                  description: 'Total amount of the order.'
                  example: 100.0
                  nullable: false
                items:
                  type: array
                  description: 'Items of the order.'
                  example:
                    -
                      name: item1
                      price: 10.0
                  items:
                    type: string
              required:
                - order_number
                - total_amount
                - items
      security: []
  '/api/orders/{orderNumber}':
    get:
      summary: 'Show order'
      operationId: showOrder
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    order_number: '12345'
                    total_amount: 100.5
                    status: pending
                    items:
                      -
                        id: 1
                        name: null
                        quantity: 1
                        price: 50.25
                      -
                        id: 2
                        name: null
                        quantity: 2
                        price: 25.12
                    created_at: '2024-12-20T16:06:13.000000Z'
                    updated_at: '2024-12-20T16:06:13.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      order_number:
                        type: string
                        example: '12345'
                      total_amount:
                        type: number
                        example: 100.5
                      status:
                        type: string
                        example: pending
                      items:
                        type: array
                        example:
                          -
                            id: 1
                            name: null
                            quantity: 1
                            price: 50.25
                          -
                            id: 2
                            name: null
                            quantity: 2
                            price: 25.12
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: null
                            quantity:
                              type: integer
                              example: 1
                            price:
                              type: number
                              example: 50.25
                      created_at:
                        type: string
                        example: '2024-12-20T16:06:13.000000Z'
                      updated_at:
                        type: string
                        example: '2024-12-20T16:06:13.000000Z'
      tags:
        - Order
      security: []
    parameters:
      -
        in: path
        name: orderNumber
        description: 'Order number.'
        example: '123456'
        required: true
        schema:
          type: string
tags:
  -
    name: Order
    description: ''
